[package]
name = "plan-a"
version = "0.1.0"
edition = "2021"

[dependencies]
adb_client = "1.0.6"
chrono = "0.4.38"
image = "0.24"
imageproc = "0.23"
mdns-sd = "0.11.3"
regex = "1.10.6"
template-matching = { version = "0.2.0", features = ["image"] }

[patch.crates-io]
adb_client = { path = "../adb_client/adb_client" }
